from typing import Protocol

from src.users.domain.user import User


class IUserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def get_by_id(self, user_id: str) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def delete(self, user_id: str) -> None: ...
