from typing import Protocol

from src.posts.domain.post import Post


class IPostRepository(Protocol):
    async def add(self, post: Post) -> None: ...

    async def get_by_id(self, post_id: str) -> Post | None: ...

    async def list_by_user_id(self, user_id: str) -> list[Post]: ...

    async def delete(self, post_id: str) -> None: ...
